[build]
  command = "ng build --configuration production"
  publish = "dist/mi-app-ng16" # ← cambia si tu carpeta de build tiene otro nombre

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200